-- -- DEV ONLY - Brute Force DROP DB ( for local dev and unit test)
--
-- SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE
--   usename = 'postgres' OR datname = 'db';
--
-- DROP DATABASE IF EXISTS db;
-- DROP USER IF EXISTS postgres;

-- DEV ONLY - Dev only password ( for local dev and unittest)
-- CREATE USER postgres PASSWORD 'postgres';
-- CREATE DATABASE db owner postgres ENCODING =  'UTF-8';
