[env]
RUST_LOG="rust_web_app=debug,axum=debug,tower_http=debug"


SERVICE_DB_URL="postgres://posgres:postgrest@localhost:5432/db"

SERVICE_PWD_KEY="CKUGFOD9_2Qf6Pn3ZFRYgPYb8ht4vKqEG9PGMXTB7497bT0367DjoaD6ydFnEVaIRda0kKeBZVCT5Hb62m2sCA"

SERVICE_TOKEN_KEY="wYqgapsU0N7dxV7oo5NjccY3j-_69b8I1gSxxHoz5yqGYpJU67OFrI8uGkHpQNkXrW751ZEpG0v6V9n2-cFoxA"
SERVICE_TOKEN_DURATION_SEC="1800" # 30 minutes

## -- ConfigMap

# This will be relative to Cargo.toml
# In deployed images, probably use absolute path.
SERVICE_WEB_FOLDER="web-folder/"
